title: Enable a workflow with GitHub Actions
tagline: Enable a workflow with GitHub Actions
description: Enable a workflow with GitHub Actions
tags:
  - GitHub Actions
  - Workflows
template:
  name: actions-workflow
  repo: actions-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.0_welcome.md
    
# Repo artifacts:
# 1. Issue: Welcome
# 2. PR: Add branch cleanup workflow
# 3. Issue: Create a deployment workflow
# 4. PR: Add deployment workflow
# 5. Issue: Improve the deployment workflow
# 6. PR: Improve the deployment workflow
# 7. Issue: Notify on deployment
# 8. PR: Add deployment notification

steps:

# 1
- title: Create a workflow file
  description: Create a workflow file
  event: pull_request
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: edited
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add branch cleanup workflow
    else:
    - type: respond
      with: e-pr-title.md
      data:
        expected: Add branch cleanup workflow
        got: '%payload.pull_request.title%'
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: 'on = "pull_request"'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-event.md
      data:
        expected: pull_request
  - type: respond
    with: 01.0_add-action.md

# 2
- title: Add the branch cleanup action
  description: Add the branch cleanup action
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: createReview
    body: 02.0_wait-for-cleanup.md
    event: APPROVE
    data:
      repo: '%payload.repository.html_url%'

# 3
- title: Run the branch cleanup action
  description: Run the branch cleanup action
  event: delete
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.ref_type%'
      operator: ===
      right: branch
    - left: '%payload.sender.login%'
      operator: ===
      right: github-actions[bot]
  - type: createIssue
    title: Create a deployment workflow
    body: 04.1_deployment-workflow.md
    action_id: deployIssue
  - type: respond
    issue: Add branch cleanup workflow
    with: 04.0_branch-cleaned-up.md
    data:
      url: '%actions.deployIssue.data.html_url%'

# 4
- title: Create a deployment workflow
  description: Create a deployment workflow
  event: pull_request.opened
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: respond
    with: 05.0_add-secret.md

# 5
- title: Store a secret on your GitHub repository
  description: Store a secret on your GitHub repository
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: respond
    with: 06.0_wait-for-deployment.md

# 6
- title: Deploy on Zeit Now
  description: Deploy on Zeit Now
  event: check_run.completed
  actions:
  - type: gate
    left: '%payload.check_run.external_id%'
    operator: ===
    right: actions/zeit-now@master
    # TODO: use multiple gates and don't act on pending checks
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_run.pull_requests.0.number%'
      with: 03.1_e-no-run.md
      data:
        repo: '%payload.repository.html_url%'
  - type: createReview
    body: 07.0_deployed.md
    event: APPROVE
    pullRequest: '%payload.check_run.pull_requests.0.number%'

# 7
- title: Merge the deployment pull request
  description: Merge the deployment pull request
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Improve the deployment function
    body: improve-deployment.md
    action_id: improvementIssue
  - type: respond
    with: goto-improvement.md
    data:
      url: '%actions.improvementIssue.data.html_url%'

# 8
- title: Pass arguments to the action
  description: Pass arguments to the action
  event: pull_request.opened
  actions:
  - type: respond
    with: explain-args.md

# 9
- title: Chain actions in a workflow
  description: Chain actions in a workflow
  event: pull_request.synchronize
  actions:
  - type: respond
    with: capture-url.md

# 10
- title: Capture the output from an existing action
  description: Capture the output from an existing action
  event: pull_request.synchronize
  actions:
  - type: respond
    with: alias-url.md

#11
- title: Alias the deployment
  description: Alias the deployment
  event: pull_request.synchronize
  actions:
  - type: createReview
    body: deployed-and-aliased.md
    event: APPROVE
    data:
      url: 'https://%payload.after%.now.sh/'

#12
- title: Merge your improved deployment workflow
  description: Merged your improved deployment workflow
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Notify on deployment
    body: notify.md
    action_id: improvementIssue
  - type: respond
    with: goto-improvement.md
    data:
      url: '%actions.improvementIssue.data.html_url%'

# 13
- title: Send a deployment notification
  description: Send a deployment notification
  event: pull_request.opened
  actions:
  - type: createReview
    body: notified.md
    event: APPROVE

# 14
- title: Merge the deployment notification
  description: Merge the deployment notification
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Congratulations
    body: congratulations.md

    


# 9 Access the runtime environment for an action
#   learner adds the alias action

# 10 Use arguments with an action
#   learner adds the deploy > deploy.txt argument to deploy action (accessed by alias)
#   learner adds the alias argument to the alias action

# 11 Notify your phone of a deployment
#   learner adds nexmo/sms action
#   learner sets environment variables
#   learner sets arguments