title: Enable a workflow with GitHub Actions
tagline: Enable a workflow with GitHub Actions
description: Enable a workflow with GitHub Actions
tags:
  - GitHub Actions
  - Workflows
template:
  name: actions-workflow
  repo: actions-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.0_welcome.md
    
# Repo artifacts:
# 1. Issue: Welcome
# 2. PR: Add branch cleanup workflow
# 3. Issue: Create a deployment workflow
# 4. PR: Add deployment workflow
# 5. Issue: Improve the deployment workflow
# 6. PR: Improve the deployment workflow
# 7. Issue: Notify on deployment
# 8. PR: Add deployment notification

steps:

# 1
- title: Create a workflow file
  description: Create a workflow file
  event: pull_request
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: edited
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add branch cleanup workflow
    else:
    - type: respond
      with: e-pr-title.md
      data:
        expected: Add branch cleanup workflow
        got: '%payload.pull_request.title%'
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: 'on = "pull_request"'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-event.md
      data:
        expected: pull_request
  - type: respond
    with: 01.0_add-action.md

# 2
- title: Add the branch cleanup action
  description: Add the branch cleanup action
  event: pull_request.synchronize
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add branch cleanup workflow
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: 'uses = "jessfraz/branch-cleanup-action@master"'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-wrong-action.md
      data:
        expected: jessfraz/branch-cleanup-action@master
  - type: respond
    with: 02.0_wait-for-cleanup.md

# 3
- title: Run the branch cleanup action
  description: Run the branch cleanup action
  # this check_run is safe since the PR would've been opened long ago
  event: check_run.completed
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.check_run.external_id%'
      operator: ===
      right: jessfraz/branch-cleanup-action@master
    - left: '%payload.check_run.status%'
      operator: ===
      right: completed
  - type: gate
    gates:
    - left: '%payload.check_run.conclusion%'
      operator: ===
      right: success
    - left: '%payload.check_run.conclusion%'
      operator: ===
      right: neutral
    else:
    - type: respond
      issue: Add branch cleanup workflow
      with: e-action-didnt-run.md
  - type: createIssue
    title: Create a deployment workflow
    body: 04.1_deployment-workflow.md
    action_id: deployIssue
  - type: createReview
    pullRequest: Add branch cleanup workflow
    body: 04.0_branch-cleaned-up.md
    event: APPROVE
    data:
      url: '%actions.deployIssue.data.html_url%'

# 4
- title: Create a deployment workflow
  description: Create a deployment workflow
  event: pull_request
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: edited
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add deployment workflow
    else:
    - type: respond
      with: e-pr-title.md
      data:
        expected: Add deployment workflow
        got: '%payload.pull_request.title%'
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: 'uses = "actions/zeit-now@master"'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-wrong-action.md
      data:
        expected: actions/zeit-now@master
  - type: respond
    with: 05.0_add-secret.md

# 5
- title: Store a secret on your GitHub repository
  description: Store a secret on your GitHub repository
  event: pull_request.synchronize
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: '/secrets\s*=\s*\[\s*"ZEIT_TOKEN",*\s*\]/g'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-no-token.md
      data:
        expected: ZEIT_TOKEN
  - type: respond
    with: 06.0_wait-for-deployment.md

# 6
- title: Deploy on Zeit Now
  description: Deploy on Zeit Now
  event: check_run.completed
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.check_run.external_id%'
      operator: ===
      right: actions/zeit-now@master
    - left: '%payload.check_run.status%'
      operator: ===
      right: completed
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: Add branch cleanup workflow
      with: e-action-didnt-run.md
  - type: createReview
    body: 07.0_deployed.md
    event: APPROVE
    pullRequest: Add deployment workflow

# 7
- title: Merge the deployment pull request
  description: Merge the deployment pull request
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Improve the deployment function
    body: improve-deployment.md
    action_id: improvementIssue
  - type: respond
    with: goto-improvement.md
    data:
      url: '%actions.improvementIssue.data.html_url%'

# 8
- title: Pass arguments to the action
  description: Pass arguments to the action
  event: pull_request
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: edited
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Improve the deployment workflow
    else:
    - type: respond
      with: e-pr-title.md
      data:
        expected: Improve the deployment workflow
        got: '%payload.pull_request.title%'
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: '/args\s*=\s*"-e GITHUB_SHA=\$GITHUB_SHA -e GITHUB_ACTOR=\$GITHUB_ACTOR"/g'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-bad-args.md
      data:
        expected: -e GITHUB_SHA=$GITHUB_SHA -e GITHUB_ACTOR=$GITHUB_ACTOR
  - type: respond
    with: explain-args.md

# 9
- title: Chain actions in a workflow
  description: Chain actions in a workflow
  event: pull_request.synchronize
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: 'action "alias"'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-expected-label.md
      data:
        expected: alias
  - type: gate
    left: '/args\s*=\s*"alias"/g'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-bad-args.md
      data:
        expected: alias
  - type: respond
    with: capture-url.md

# 10
- title: Capture the output from an existing action
  description: Capture the output from an existing action
  event: pull_request.synchronize
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: '/args\s*=\s*"-e GITHUB_SHA=\$GITHUB_SHA -e GITHUB_ACTOR=\$GITHUB_ACTOR deploy > deploy\.txt"/g'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-bad-args.md
      data:
        expected: -e GITHUB_SHA=$GITHUB_SHA -e GITHUB_ACTOR=$GITHUB_ACTOR deploy > deploy.txt
  - type: respond
    with: alias-url.md

#11
- title: Alias the deployment
  description: Alias the deployment
  event: pull_request.synchronize
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: '/args = "alias `cat deploy.txt` \$GITHUB_SHA"/g'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-bad-args.md
      data:
        expected: alias \`cat deploy.txt\` $GITHUB_SHA
  - type: respond
    with: deployed-and-aliased.md
    data:
      url: 'https://%payload.after%.now.sh/'

- title: Run the aliased deployment
  description: Run the aliased deployment
  event: check_run.completed
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.check_run.external_id%'
      operator: ===
      right: actions/zeit-now@master
    - left: '%payload.check_run.status%'
      operator: ===
      right: completed
    - left: '%payload.check_run.name%'
      operator: ===
      right: alias # we validated this in an earlier step
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: Improve the deployment workflow
      with: e-action-didnt-run.md
  - type: createReview
    body: merge-aliased.md
    event: APPROVE
    pullRequest: Improve the deployment workflow

#12
- title: Merge your improved deployment workflow
  description: Merged your improved deployment workflow
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Notify on deployment
    body: notify.md
    action_id: improvementIssue
  - type: respond
    with: goto-improvement.md
    data:
      url: '%actions.improvementIssue.data.html_url%'

# 13
- title: Send a deployment notification
  description: Send a deployment notification
  event: pull_request.opened
  actions:
  - type: getFileContents
    action_id: fileContents
    filename: '.github/main.workflow'
  - type: gate
    left: 'uses = "nexmo-community/nexmo-sms-action@master"'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-wrong-action.md
      data:
        expected: nexmo-community/nexmo-sms-action@master
  - type: gate
    left: '/^(?=.*"NEXMO_API_KEY",*)(?=.*"NEXMO_API_SECRET",*)(?=.*"NEXMO_NUMBER",*)(?=.*"PHONE",*).*$/gm'
    operator: test
    right: '%actions.fileContents%'
    else:
    - type: respond
      with: e-no-token.md
      data:
        expected: NEXMO_API_KEY, NEXMO_API_SECRET, NEXMO_NUMBER, and PHONE
  - type: createReview
    body: notified.md
    event: APPROVE

# 14
- title: Merge the deployment notification
  description: Merge the deployment notification
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Congratulations
    body: congratulations.md
    action_id: congratsIssue
  - title: respond
    with: goto-congratulations.md
    data:
      url: '%actions.congratsIssue.data.html_url%'

    


# 9 Access the runtime environment for an action
#   learner adds the alias action

# 10 Use arguments with an action
#   learner adds the deploy > deploy.txt argument to deploy action (accessed by alias)
#   learner adds the alias argument to the alias action

# 11 Notify your phone of a deployment
#   learner adds nexmo/sms action
#   learner sets environment variables
#   learner sets arguments