title: Enable a workflow with GitHub Actions
tagline: Enable a workflow with GitHub Actions
description: Enable a workflow with GitHub Actions
tags:
  - GitHub Actions
  - Workflows
template:
  name: actions-workflow
  repo: actions-workflow-template
before:
  - type: updateBranchProtection

  - type: createIssue
    title: Welcome
    body: welcome.md
# Repo artifacts:
# 1. Issue: Welcome
# 2. PR: Add branch cleanup workflow
# 3. Issue: Create a deployment workflow
# 4. PR: Add deployment workflow

steps:

# 1 Create the workflow file 
- title: Create a workflow file
  description: Create a workflow file
  event: pull_request.opened
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: add-action.md

# 2 Add the branch cleanup action
- title: Add the branch cleanup action
  description: Add the branch cleanup action
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: wait-for-cleanup.md

# 3 Wait for the branch cleanup action to run
- title: Wait for the branch cleanup action to run
  description: Wait for the branch cleanup action to run
  event: check_suite.completed
  actions:
  - type: gate
    left: '%payload.check_suite.app.name%'
    operator: ===
    right: GitHub Actions
  - type: gate
    left: '%payload.check_suite.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_suite.pull_requests.0.number%'
      with: e-no-run.md
      data:
        repo: '%payload.repository.html_url%'
  - type: createReview
    pullRequest: '%payload.check_suite.pull_requests.0.number%'
    body: workflow-success.md
    event: APPROVE
    data:
      repo: '%payload.repository.html_url%'

# 4 title: Run the branch cleanup action
- title: Run the branch cleanup action
  description: Run the branch cleanup action
  event: delete
  actions: 
  - type: gate
    every: true
    gates:
    - left: '%payload.ref_type%'
      operator: ===
      right: branch
    - left: '%payload.sender.login%'
      operator: ===
      right: github-actions[bot]
  - type: respond
    issue: Add branch cleanup workflow
    with: branch-cleaned-up.md
  - type: createIssue
    title: Create a deployment workflow
    body: deployment-workflow.md

# 5 
- title: Create a deployment workflow
  description: Create a deployment workflow
  event: pull_request.opened
  actions: 
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: add-secret.md

# 6
- title: Store a secret on your GitHub repository
  description: Store a secret on your GitHub repository
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: e-no-workflow.md
  - type: respond
    with: wait-for-deployment.md

# 7 
- title: Deploy on Zeit Now
  description: Deploy on Zeit Now
  event: check_suite.completed
  actions:
  - type: gate
    left: '%payload.check_suite.app.name%'
    operator: ===
    right: GitHub Actions
  - type: gate
    left: '%payload.check_suite.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_suite.pull_requests.0.number%'
      with: e-no-run.md
      data:
        repo: '%payload.repository.html_url%'
  - type: respond
    issue: '%payload.check_suite.pull_requests.0.number%'
    with: deployed.md

# 6 check_suite.completed - the deployment happened, missing key
# 7 pull_request.synchronize - add an api key
# 8 check_suite.completed - the deployment happened, succeeded
# 9 pull_request.closed - merge the workflow, but no notification exists