title: Enable a workflow with GitHub Actions
tagline: Enable a workflow with GitHub Actions
description: Enable a workflow with GitHub Actions
tags:
  - GitHub Actions
  - Workflows
template:
  name: actions-workflow
  repo: actions-workflow-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00.0_welcome.md
    
# Repo artifacts:
# 1. Issue: Welcome
# 2. PR: Add branch cleanup workflow
# 3. Issue: Create a deployment workflow
# 4. PR: Add deployment workflow
# 5. Issue: Improve the deployment workflow

steps:

# 1 Create the workflow file
- title: Create a workflow file
  description: Create a workflow file
  event: pull_request.opened
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: respond
    with: 01.0_add-action.md

# 2 Add the branch cleanup action
- title: Add the branch cleanup action
  description: Add the branch cleanup action
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: createReview
    body: 02.0_wait-for-cleanup.md
    event: APPROVE
    data:
      repo: '%payload.repository.html_url%'

# 4 title: Run the branch cleanup action
- title: Run the branch cleanup action
  description: Run the branch cleanup action
  event: delete
  actions:
  - type: gate
    every: true
    gates:
    - left: '%payload.ref_type%'
      operator: ===
      right: branch
    - left: '%payload.sender.login%'
      operator: ===
      right: github-actions[bot]
  - type: createIssue
    title: Create a deployment workflow
    body: 04.1_deployment-workflow.md
    action_id: deployIssue
  - type: respond
    issue: Add branch cleanup workflow
    with: 04.0_branch-cleaned-up.md
    data:
      url: '%actions.deployIssue.data.html_url%'

# 5
- title: Create a deployment workflow
  description: Create a deployment workflow
  event: pull_request.opened
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: respond
    with: 05.0_add-secret.md

# 6
- title: Store a secret on your GitHub repository
  description: Store a secret on your GitHub repository
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/^.github/main.workflow$/
    else:
      type: respond
      with: 01.1_e-no-workflow.md
  - type: respond
    with: 06.0_wait-for-deployment.md

# 7
- title: Deploy on Zeit Now
  description: Deploy on Zeit Now
  event: check_run.completed
  actions:
  - type: gate
    left: '%payload.check_run.external_id%'
    operator: ===
    right: actions/zeit-now@master
  - type: gate
    left: '%payload.check_run.conclusion%'
    operator: ===
    right: success
    else:
    - type: respond
      issue: '%payload.check_run.pull_requests.0.number%'
      with: 03.1_e-no-run.md
      data:
        repo: '%payload.repository.html_url%'
  - type: createReview
    body: 07.0_deployed.md
    event: APPROVE
    pullRequest: '%payload.check_run.pull_requests.0.number%'

# 8
- title: Merge the deployment pull request
  description: Merge the deployment pull request
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createIssue
    title: Improve the deployment function
    body: improve-deployment.md
    action_id: improvementIssue
  - type: respond
    with: goto-improvement.md
    data:
      url: '%actions.improvementIssue.data.html_url%'

# 9 
- title: Pass arguments to the action
  description: Pass arguments to the action
  event: pull_request.opened
  actions:
  - type: respond
    with: explain-args.md

# 10
- title: Chain actions in a workflow
  description: Chain actions in a workflow
  event: pull_request.synchronize
  actions:
  - type: respond
    with: capture-url.md

# 11
- title: Capture the output from an existing action
  description: Capture the output from an existing action
  event: pull_request.synchronize
  actions:
  - type: respond
    with: placeholder.md


# 9 Access the runtime environment for an action
#   learner adds the alias action

# 10 Use arguments with an action
#   learner adds the deploy > deploy.txt argument to deploy action (accessed by alias)
#   learner adds the alias argument to the alias action

# 11 Notify your phone of a deployment
#   learner adds nexmo/sms action
#   learner sets environment variables
#   learner sets arguments